image: node:10.15.3-alpine

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

validate:
  stage: validate
  script:
    - echo "Validate"
    - npm run lint

codecheck:
  stage: validate
  script:
    - echo "Code Check"

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: npm test

deploy-heroku-production:
  stage: deploy
  script:
    - echo "Deploy App to Heroku"
    - apk update && apk upgrade
    - apk add --no-cache git ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=backend-enginer-pagarme --api-key=$HEROKU_KEY
    - git remote add heroku https://itor.isaias:$HEROKU_KEY@git.heroku.com/backend-enginer-pagarme.git
    - git push heroku ${CI_COMMIT_REF_NAME}
  environment:
    name: production
    url: https://backend-enginer-pagarme.herokuapps.com
  when: manual
  only:
    - master
