image: node:10.15.3-alpine

stages:
  - validate
  - test
  - coverage
  - build
  - artifact
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

quality:
  stage: validate
  script:
    - echo "Linter code"
    - npm run lint

unit-test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage

coverage:
  stage: coverage
  script:
    - echo "Coverage"
    - npm install codecov
    - ./node_modules/.bin/codecov --token=$TOKEN_CODECOV

deploy-prod:
  stage: deploy
  before_script:
    - git checkout master
  script:
    - apk add --no-cache git
    - git remote add heroku https://itor.isaias:$HEROKU_KEY@git.heroku.com/backend-enginer-pagarme.git
    - git push heroku HEAD:master -f
  environment:
    name: producao
    url: https://backend-enginer-pagarme.herokuapp.com
  only:
    - master
