image: node:10.15.3-alpine

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

validate:
  stage: validate
  script:
    - echo "Validate"
    - npm run lint

codecheck:
  stage: validate
  script:
    - echo "Code Check"

testing_testing:
  stage: test
  script: npm test

deploy-heroku-production:
  stage: deploy
  image: ruby:latest
  script:
    - echo "Deploy App to Heroku"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=backend-enginer-pagarme --api-key=$HEROKU_KEY
  environment:
    name: production
    url: https://backend-enginer-pagarme.herokuapps.com
  when: manual
  only:
    - master
